import { useEffect, useState } from 'react'
import Hero from './components/Hero'
import About from './components/About'
import Services from './components/Services'
import Contact from './components/Contact'

interface ContentData {
	hero?: any
	about?: any
	services?: any
	contact?: any
}

function App() {
	const [content, setContent] = useState<ContentData>({})
	const [loading, setLoading] = useState(true)

	useEffect(() => {
		// Load content from local JSON files (generated by Decap CMS)
		const loadContent = async () => {
			try {
				const responses = await Promise.all([
					fetch('/content/hero.json'),
					fetch('/content/about.json'),
					fetch('/content/services.json'),
					fetch('/content/contact.json'),
				])

				const [hero, about, services, contact] = await Promise.all(
					responses.map(r => r.ok ? r.json() : null)
				)

				setContent({ hero, about, services, contact })
			} catch (error) {
				console.error('Failed to load content:', error)
			} finally {
				setLoading(false)
			}
		}

		loadContent()
	}, [])

	if (loading) {
		return (
			<div className="flex items-center justify-center min-h-screen">
				<div className="text-2xl">Loading...</div>
			</div>
		)
	}

	return (
		<div className="min-h-screen bg-white">
			<Hero data={content.hero} />
			<About data={content.about} />
			<Services data={content.services} />
			<Contact data={content.contact} />
		</div>
	)
}

export default App
